---
name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches: [master]
env:
  IMAGE_NAME: server_power_control
jobs:
  push-ghcr:
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Generate Image Version
        run: echo IMAGE_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build && Push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |-
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push to Docker Hub
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_VERSION}
          docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_VERSION}
